#! /bin/bash

if [ -n "$1" ]; then
	echo "\$TTL	300
@	IN	SOA	ns.toon-croonenberghs.sb.uclllabs.be $1.toon-croonenberghs.sb.uclllabs.be.(
			700	; Serial
			300	; Refresh
			300	; Retry
			300	; Expire
			300)	; Negative Cashe TTL
; A records for name servers
@	IN	NS	ns.toon-croonenberghs.sb.uclllabs.be.
ns	IN	A	193.191.177.229
@	IN	A	193.191.177.229" > /etc/bind/zones/$1.toon-croonenberghs.sb.uclllabs.be
echo -e "
zone \"$1.toon-croonenberghs.sb.uclllabs.be\"{
	type master;
	file \"/etc/bind/zones/$1.toon-croonenberghs.sb.uclllabs.be\";
	notify yes;
};" >> /etc/bind/named.conf.local

echo -e "$1	IN	NS	ns.toon-croonenberghs.sb.uclllabs.be." >> /etc/bind/db.toon-croonenberghs.sb.uclllabs.be
SERIAL_NUM=$(grep -Po '\d+(?=\s+; Serial)' /etc/bind/db.toon-croonenberghs.sb.uclllabs.be)
SERIAL_LIN=$(grep -Po '\s+; Serial' /etc/bind/db.toon-croonenberghs.sb.uclllabs.be)x
SERIAL_ALL=$(grep -Po '\d+\s+; Serial' /etc/bind/db.toon-croonenberghs.sb.uclllabs.be)
NEW_NUM=$(("$SERIAL_NUM" + 1))
sed -i "s/$SERIAL_ALL/$NEW_NUM$SERIAL_LIN/g" /etc/bind/db.toon-croonenberghs.sb.uclllabs.be

systemctl restart bind9

else
	echo "no string"
fi
